### ISSUE TITLE
EDscout is not displaying data.

### ISSUE THREAD

**Issue by Adrix12334** [joncage/ed-scout#156] opened 2021-01-12 12:23 UTC
EDscout is not displaying data in the log it is shown to get the data but it is not shown in the gui. Does not mater if i restart the game or the app. Remote access also have that problem. I have reinstaled the program a few times and it still does not work. (Sorry for any speling mistakes,  English is not my native language.) 
[EDScout-2021-01-12-12-04-59.log](https://github.com/joncage/ed-scout/files/5802001/EDScout-2021-01-12-12-04-59.log)
[EDScout-2021-01-12-12-10-25.log](https://github.com/joncage/ed-scout/files/5802002/EDScout-2021-01-12-12-10-25.log)
[EDScout-2021-01-12-12-11-54.log](https://github.com/joncage/ed-scout/files/5802003/EDScout-2021-01-12-12-11-54.log)

**Comment by KingGLEB** [comment] 2021-01-12 14:32
The EDSM website from which the program takes information does not work. 
EDSM is down ->> EDScout not work.

**Comment by Adrix12334** [comment] 2021-01-12 14:34
Than you for the answer

**Comment by bbbkada** [comment] 2021-01-14 20:26
I have the same issue, EDSM is back up (maybe new location ?).

**Comment by Kepas-Beleglorn** [comment] 2021-01-14 21:16
EDSM is back up, but it seems the api endpoints on https://www.edsm.net/api-v1/* still have some issues. But it seems someone is already working on that.

**Comment by Deadweasel** [comment] 2021-01-16 14:19
Confirmed things seem to be back up and working properly once again!

**Comment by Kepas-Beleglorn** [comment] 2021-01-16 15:14
Acknowledged. EDScout working like a charm again.

**Comment by Cathprotech** [comment] 2021-01-16 18:27
I just intalled this the other day and wasn't working. Tried all sorts to get it to run, then found this thread, so fair enough.
However, I tried it today and, yes it worked but just once. I tried a remote view and nothing. I rebooted everything and tried again. The onlything I get is my current location and that takes about 5 minutes before it comes up. 
Are there still server problems or is there something I need to do localy?
Thanks

**Comment by Kepas-Beleglorn** [comment] 2021-01-16 18:39
@Cathprotech 
The EDMS services are back up and running perfectly by now.

You could try resetting the EDScout working directory (On Windows 10: %userprofile%\AppData\Local\EDScout) by deleting everything except for the ini file. Then try setting the "force_polling" to "True".
It happened to me, that EDScout stopped working when I set the "no_app" to "True". However the remote access worked even after closing the EDScouts own browser window.

Also, EDScout happens to get stuck on plotting very long routes (1000+ ( ? ) jumps), too.

If you want to use the remote view in a browser on a tablet you could also try "spacedeck" (server on your PC, client app on your tablet). The tablet will then be available as an additional monitor for your PC.

**Comment by Cathprotech** [comment] 2021-01-16 18:59
Hi,
Ok, I tried deleting everything and re-running.
It does come up with current location but if I refresh the screen then it loses that.
I looked in the log and used this line "https://www.edsm.net/en/system/bodies/id/9353197/name/Synuefe+GA-J+c11-2" which takes me to the EDSM page where it says "We do not have any data concerning the celestial bodies in this system yet." which is strange because about an hour ago it did come up with all the bodies in that system and ED Scout had them listed, although briefly.

**Comment by Kepas-Beleglorn** [comment] 2021-01-16 19:13
@Cathprotech After refreshing the page try re-plotting your route. The entries should be up to date after that. The celestial bodies of the current system should be shown after you used DS or FSS.

**Comment by Cathprotech** [comment] 2021-01-17 00:23
Hi,
It seems to be working now, both on screen and remote.
Thanks

**Comment by Kepas-Beleglorn** [comment] 2021-01-25 18:12
Again there seems to be an issue with ED Scout displaying data. This time for a three jumps route.
[EDScout-2021-01-25-18-09-04.log](https://github.com/joncage/ed-scout/files/5868650/EDScout-2021-01-25-18-09-04.log)

The diagnostic build shows this:
`D:\Tools\EliteDangerous\EDScout>EDScout.exe
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "EDScoutWebUI\EDScout.py", line 173, in receive_and_forward
  File "EDScoutCore\EDScout.py", line 47, in trigger_current_journal_check
  File "EDScoutCore\JournalInterface.py", line 189, in trigger_current_journal_check
  File "EDScoutCore\JournalInterface.py", line 193, in _on_journal_change
  File "EDScoutCore\EDScout.py", line 168, in on_journal_change
  File "EDScoutCore\EDScout.py", line 174, in process_new_journal_entries
  File "EDScoutCore\EDScout.py", line 143, in process_journal_change
  File "EDScoutCore\EDScout.py", line 204, in on_new_route
  File "EDScoutCore\EDScout.py", line 181, in get_edsm_system_report
  File "EDScoutCore\EDSMInterface.py", line 72, in get_system_estimated_value
TypeError: exceptions must derive from BaseException

Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "watchdog\observers\api.py", line 203, in run
  File "watchdog\observers\api.py", line 376, in dispatch_events
  File "watchdog\events.py", line 452, in dispatch
  File "watchdog\events.py", line 336, in dispatch
  File "EDScoutCore\JournalInterface.py", line 144, in on_modified
  File "EDScoutCore\JournalInterface.py", line 193, in _on_journal_change
  File "EDScoutCore\EDScout.py", line 168, in on_journal_change
  File "EDScoutCore\EDScout.py", line 174, in process_new_journal_entries
  File "EDScoutCore\EDScout.py", line 143, in process_journal_change
  File "EDScoutCore\EDScout.py", line 204, in on_new_route
  File "EDScoutCore\EDScout.py", line 181, in get_edsm_system_report
  File "EDScoutCore\EDSMInterface.py", line 72, in get_system_estimated_value
TypeError: exceptions must derive from BaseException`

**Comment by Kepas-Beleglorn** [comment] 2021-01-25 19:36
Another exception happend on entering system GRAEA EOQ XP-T A85-0
`Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "watchdog\observers\api.py", line 203, in run
  File "watchdog\observers\api.py", line 376, in dispatch_events
  File "watchdog\events.py", line 452, in dispatch
  File "watchdog\events.py", line 336, in dispatch
  File "EDScoutCore\JournalInterface.py", line 144, in on_modified
  File "EDScoutCore\JournalInterface.py", line 193, in _on_journal_change
  File "EDScoutCore\EDScout.py", line 168, in on_journal_change
  File "EDScoutCore\EDScout.py", line 174, in process_new_journal_entries
  File "EDScoutCore\EDScout.py", line 152, in process_journal_change
  File "EDScoutCore\EDScout.py", line 93, in create_system_report
  File "EDScoutCore\EDSMInterface.py", line 34, in get_system
TypeError: exceptions must derive from BaseException
[EDScout-2021-01-25-19-17-30.log](https://github.com/joncage/ed-scout/files/5869207/EDScout-2021-01-25-19-17-30.log)
`

**Comment by joncage** [comment] 2021-02-26 01:24
Next major release should sort this (I've added retries and handling for EDSM not responding) if it is, as I expect, down to EDSM connectivity.

**Comment by SirCanucklehead** [comment] 2021-02-27 00:24
Also Having this issue. Updated to 1.8.0. Was working yesterday, today it sits at "Waiting for data" perpetually.

[EDScout-2021-02-27-00-04-22.log](https://github.com/joncage/ed-scout/files/6053355/EDScout-2021-02-27-00-04-22.log)

**Comment by joncage** [comment] 2021-02-27 01:09
> Why the displayed data gets lost on refreshing the page is a question only @joncage could answer.

Yeah, it's a weakness in the way I wrote EDScout. It just launches a browser then sends data to it but there's nothing to persist or re-send that data if you refresh the page.

Really I think I need to do something a bit more intelligent in the back end in terms of getting the GUI to request data when it connects. It does something like that initially but needs a way to cache the current state of the GUI so it can jst re-send the pertinent information.

**Comment by joncage** [comment] 2021-02-27 01:20
> Also Having this issue. Updated to 1.8.0. Was working yesterday, today it sits at "Waiting for data" perpetually.
> 
> [EDScout-2021-02-27-00-04-22.log](https://github.com/joncage/ed-scout/files/6053355/EDScout-2021-02-27-00-04-22.log)

Well that's no good! Okay, two things to check:

1. Right-click on the GUI, pick "inspect" and "Console". Do you see any errors?
2. I doubt this is the cause but it looks like EDScout is having a hard time trying to replicate your HUD colours (see excerpt 1 below). Any chance I could see that file?
3. Looks like you've probably launched a few instances of EDScout based on the log messages I can see. making sure they are all completely killed off using task manager and then relaunch and see if that helps. 

**Log excerpt 1**

```
2021-02-27T00:04:22.273Z - EDScoutWebUI-EDScout - INFO - Looking for HUD overrides in C:\Users\kiera\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\GraphicsConfigurationOverride.xml
2021-02-27T00:04:22.273Z - EDScoutWebUI-EDScout - ERROR - Failed to interpret HUD overrides; Please check your file is of the format described in https://arkku.com/elite/hud_editor/
2021-02-27T00:04:22.274Z - EDScoutWebUI-EDScout - ERROR - no element found: line 3, column 0
Traceback (most recent call last):
  File "EDScoutWebUI\EDScout.py", line 230, in remap_css_to_match_hud
  File "EDScoutWebUI\HudColourAdjuster.py", line 38, in get_matrix_values
  File "xml\etree\ElementTree.py", line 1197, in parse
  File "xml\etree\ElementTree.py", line 598, in parse
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 3, column 0
```

**Log exceprt 2**

```
2021-02-27T00:04:22.255Z - EDScoutWebUI-EDScout - INFO - Found existing Scout instance PID:9040, killing off before continuing
2021-02-27T00:04:22.257Z - EDScoutWebUI-EDScout - INFO - Found existing Scout instance PID:13056, killing off before continuing
```

```
2021-02-27T00:05:49.062Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
2021-02-27T00:07:15.867Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
2021-02-27T00:08:03.942Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
2021-02-27T00:08:42.579Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
```

**Comment by SirCanucklehead** [comment] 2021-02-27 02:52
> > Also Having this issue. Updated to 1.8.0. Was working yesterday, today it sits at "Waiting for data" perpetually.
> > [EDScout-2021-02-27-00-04-22.log](https://github.com/joncage/ed-scout/files/6053355/EDScout-2021-02-27-00-04-22.log)
> 
> Well that's no good! Okay, a few things to check:
> 
> 1. Right-click on the GUI, pick "inspect" and "Console". Do you see any errors?
> 2. I doubt this is the cause but it looks like EDScout is having a hard time trying to replicate your HUD colours (see excerpt 1 below). Any chance I could see that file?
> 3. Looks like you've probably launched a few instances of EDScout based on the log messages I can see. making sure they are all completely killed off using task manager and then relaunch and see if that helps.
> 
> **Log excerpt 1**
> 
> ```
> 2021-02-27T00:04:22.273Z - EDScoutWebUI-EDScout - INFO - Looking for HUD overrides in C:\Users\kiera\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\GraphicsConfigurationOverride.xml
> 2021-02-27T00:04:22.273Z - EDScoutWebUI-EDScout - ERROR - Failed to interpret HUD overrides; Please check your file is of the format described in https://arkku.com/elite/hud_editor/
> 2021-02-27T00:04:22.274Z - EDScoutWebUI-EDScout - ERROR - no element found: line 3, column 0
> Traceback (most recent call last):
>   File "EDScoutWebUI\EDScout.py", line 230, in remap_css_to_match_hud
>   File "EDScoutWebUI\HudColourAdjuster.py", line 38, in get_matrix_values
>   File "xml\etree\ElementTree.py", line 1197, in parse
>   File "xml\etree\ElementTree.py", line 598, in parse
>   File "<string>", line None
> xml.etree.ElementTree.ParseError: no element found: line 3, column 0
> ```
> 
> **Log excerpt 2**
> 
> ```
> 2021-02-27T00:04:22.255Z - EDScoutWebUI-EDScout - INFO - Found existing Scout instance PID:9040, killing off before continuing
> 2021-02-27T00:04:22.257Z - EDScoutWebUI-EDScout - INFO - Found existing Scout instance PID:13056, killing off before continuing
> ```
> 
> ```
> 2021-02-27T00:05:49.062Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
> 2021-02-27T00:07:15.867Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
> 2021-02-27T00:08:03.942Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
> 2021-02-27T00:08:42.579Z - VersionChecker-VersionChecker - INFO - Version check: Up to date
> ```

I'm off for the night, but I'll check out the console and let you know what I find when I hop on tomorrow. 

Also, I'm using the Elite Dangerous HUD Mod to change the colours, the .xml is untouched as far as I remember but I'll take a look and send it your way tomorrow as well just to be sure.

**Comment by SirCanucklehead** [comment] 2021-02-27 15:43
Alright, so I loaded up the game, launched EDScout, let it sit for a minute but it still stays on "Waiting for nav data"

I went to Inspect/Console and this is what it showed;

Failed to load resource: the server responded with a status of 404 (NOT FOUND)
EdScout.js?2021-02-27 15:34:24.288660:777 Launching backend connections
EdScout.js?2021-02-27 15:34:24.288660:735 Objectcurrent_version: "v1.8.0"latest_version: "v1.8.0"new_release_detected: falseurl: "https://github.com/joncage/ed-scout/releases/latest"__proto__: Object
css-overrides.css:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
EdScout.js?2021-02-27 15:34:24.288660:488 {data: {…}}

Also, here's what's in my GraphicsConfigurationOverride.xml;

<?xml version="1.0" encoding="UTF-8" ?>
<GraphicsConfig>

I've meddled with it in the past but the HUD mod I'm using requires it default/blank

**Comment by joncage** [comment] 2021-03-14 01:24
Try the latest release, 1.8.2 and see if that fixes it? https://github.com/joncage/ed-scout/releases/tag/v1.8.2

**Comment by SirCanucklehead** [comment] 2021-03-14 14:30
Just gave 1.8.2 a try, works perfectly so far. Thanks for all the work you do on this, it's an amazingly useful tool.

**Closed** 2021-03-24 22:29 UTC
