### ISSUE TITLE
Trojan virus detected on 1.7.1 exe

### ISSUE THREAD

**Issue by D4VID-B** [joncage/ed-scout#131] opened 2020-10-11 22:04 UTC
Went to download the EDScout.exe and Windows defender flagged it as having a virus on it. I saw that there was a similar Issue, but the virus they reported was different to what Defender found on my machine:
![EDS_1](https://user-images.githubusercontent.com/48723686/95691281-02143c00-0bec-11eb-82d3-64e3ef563cef.PNG)
Let's hope this is also a false positive. 
Also, if possible add a hash checksum to the important files so we can verify them.
Thank you

**Comment by joncage** [comment] 2020-10-11 22:42
Submitted to MS for review - thanks for reporting: https://www.microsoft.com/en-us/wdsi/submission/b12018fa-6c58-4b06-8cd2-ebaa8c746e2d

Good idea r.e. the checksums.

**Comment by Gopher-nz** [comment] 2020-10-12 02:49
Yup got same problem v1.6 not working and all later releases cannot be downloaded. Wish I knew coding, I would offer a helping hand.

**Comment by joncage** [comment] 2020-10-12 07:32
From Microsoft...

> We have reviewed the files and we have added detection for them to the next definition update. The latest definitions information is available here: https://www.microsoft.com/en-us/wdsi/definitions.

> Thank you for contacting Microsoft.

**Comment by joncage** [comment] 2020-10-12 08:29
Try updating your virus Defs and give it another shot. I think it has less problems with the installed version too if that helps..

**Comment by D4VID-B** [comment] 2020-10-12 11:22
Tried again, with (what I think are) the latest Defs. Now getting this:
![EDS_2](https://user-images.githubusercontent.com/48723686/95740460-8ac9c100-0c5a-11eb-948e-fdefee819cd6.PNG)
Any ideas why this is happening to your files? I've been setting up a number of tools for Elite and haven't had this happen anywhere.
Also (and this is somewhat off-topic) what does the Setup-EDScout.exe do? Maybe I can try using it instead.

**Comment by joncage** [comment] 2020-10-12 11:43
My guess (and frankly I don't know) is that because I've written this in Python, used a flask web server and packaged it up with PyInstaller, that Microsoft's tools look at and say "Well this looks suspicious; Written in Python and it extracts python code and then runs it? I'd better flag this". It's becoming pretty frustrating because I have to do this every time I release another version (and apparently now multiple times).

The `Setup-EDScout.exe` is an installer that installs the executable to program files. I read somewhere that using an installer can help as viruses tend not to bother with installers so that may help and I may well ditch the portable `EDScout.exe` I'd been releasing in parallel to cut down on my work load.

I know EDDiscovery is written in C# and as that's Microsoft's language, maybe they're less suspicious of it. I think this is all part of their cunning plan to get more people writing C# and to encourage more poor developers to shell out hard earned cash to add certificates to sign the software releases.

**Comment by joncage** [comment] 2020-10-12 11:52
Submitted again: https://www.microsoft.com/en-us/wdsi/submission/6dc85a2b-6a84-44c8-9edd-59f2a6cef07e

**Comment by Rhaedas** [comment] 2020-10-12 12:10
A quick and not thorough Google suggests that this is a common thing with using PyInstaller for a few reasons. There's a number of problems and "solutions" on StackOverflow, not sure if any would apply here. But I did have a thought - could you go ahead and submit a new version's exe to MS as being okay as a step in releasing it? Why wait for user reports if it's going to be a thing, just get it into their system to look at and approve.

**Comment by D4VID-B** [comment] 2020-10-12 12:12
Yeah, I can imagine this is annoying. Which is why I hate to say this, but: 
![EDS_3](https://user-images.githubusercontent.com/48723686/95744921-30346300-0c62-11eb-9f9b-2fe79a0f85af.PNG)
This was on the Setup exe I tried downloading just now. 

Also, I appreciate you sharing the submission links, but I can't access them. Microsoft just shows this when I click the link: "You are not authorized to view details for the requested submission id (6dc85a2b-6a84-44c8-9edd-59f2a6cef07e)."
I'm logged in too - don't know if that affects things. Maybe it's a defense precaution.

**Comment by D4VID-B** [comment] 2020-10-12 12:15
Also, regarding this being in Python, maybe try contacting the devs of ED Market Connector? Their Github shows that it's 100% Python and I didn't get any antivirus hits when installing their tool

**Comment by joncage** [comment] 2020-10-12 13:08
> Also, I appreciate you sharing the submission links, but I can't access them.

To be honest, I do that mostly for my own reference to make it easy to double-check the status.

Double-checking with EDMC is a good call. Looks like they use Py2Exe rather than PyInstaller and TKinter instead of a web UI so maybe it's that or maybe they have a way of signing releases I couldn't see from a quick source-skim.

**Comment by joncage** [comment] 2020-10-12 13:29
Scanning the same .exe's I've uploaded to github from my machine I get no matches:

![image](https://user-images.githubusercontent.com/73681/95751953-385ac580-0c97-11eb-8a47-0acdeddf4c84.png)

...which just makes this all the stranger. I don't understand why defender takes such an issue with this but I'll keep on battling!

**Comment by joncage** [comment] 2020-10-12 13:40
> A quick and not thorough Google suggests that this is a common thing with using PyInstaller for a few reasons. There's a number of problems and "solutions" on StackOverflow, not sure if any would apply here. But I did have a thought - could you go ahead and submit a new version's exe to MS as being okay as a step in releasing it? Why wait for user reports if it's going to be a thing, just get it into their system to look at and approve.

I'd had the same thought but you're required to specify what detection was found and as my machine never marks them as bad in the first place that's impossible for me.

**Comment by D4VID-B** [comment] 2020-10-12 15:58
Maybe its something to do with you also being the author and having the source code on the computer, or something else related to you being the author. 
I'll wait for a bit, or until MC releases another Def or something and try again. Might try to mess around with it's settings too - maybe it's possible to make it less trigger-happy...

**Comment by joncage** [comment] 2020-10-12 16:07
> Maybe its something to do with you also being the author and having the source code on the computer, or something else related to you being the author.

Yeah, possibly. 

If I find some time I'll have a bit more of a dig into EDMC and how they package things. I note that they produce a .msi rather than a innosetup-generated .exe installer which may also be another avenue to solve this.

**Comment by joncage** [comment] 2020-10-12 20:26
Well at least for the setup file they've confirmed:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"

> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by D4VID-B** [comment] 2020-10-12 21:57
Ok. A this point I'm starting to get somewhat fed up with Windows Defender. I ran the command prompt commands and everything updated, but it's *still* flagging `Setup` as having that Trojan. Any estimate on when (if at all) you can make the checksums available for these files? That way I can at least make sure my files match yours when I override Defender to install it.
Take your time if you have too, I'm not planning to go far from the Bubble quite yet :)

**Comment by joncage** [comment] 2020-10-12 22:35
Just for you (I'll automate this later)...

![image](https://user-images.githubusercontent.com/73681/95795948-97dec280-0ce3-11eb-85b4-74bed3e1d767.png)

![image](https://user-images.githubusercontent.com/73681/95795964-a3ca8480-0ce3-11eb-8ef7-4765b365a7fb.png)

**Comment by joncage** [comment] 2020-10-12 22:40
Found an interesting tool today; Virustotal.

For EDScout.exe we get: https://www.virustotal.com/gui/file/cd63e536fe177452883eca53322bba3bb79334f3ab85a16acc6846544da2c207/detection

For the installer we get:

https://www.virustotal.com/gui/file/89572817ef584e475edf737d60e2464bf7bf8cd8563d316428e1703b63b38f21/detection

**Comment by joncage** [comment] 2020-10-12 22:45
Longer term #114 should avoid these issues... or that's the intention at least.

**Comment by joncage** [comment] 2020-10-12 22:46
Being paranoid, I ran defender over my entire drive and it came up empty for viruses (FYI).

**Comment by D4VID-B** [comment] 2020-10-12 22:53
Oh yeah, I've seen that on EDDiscovery's GitHub. He includes a screenshot of this every new release.
I guess Microsoft really does have an issue with Python for some reason...
Tomorrow, I'll try again, override Defender, get the hash from the file and stick it into Virustotal. At that point, if it's still complaining, it's getting outvoted.
As far as signing goes - since it's paid I'd almost consider it a last resort if doing things similar to EDMC isn't an option.

**Comment by joncage** [comment] 2020-10-12 22:54
Appreciate the vote of confidence and your resolve Cmdr!

o7

**Comment by D4VID-B** [comment] 2020-10-13 12:02
The hash values matched and everything seems to be working! I used the `Setup... .exe` this time. 
I do have one (fairly off-topic) question though: are you using the in-game HUD color matrix to do the UI color? Because in your screenshots and in DTEA's video it's the traditional Orange-Black, whereas mine is Green(ish)-Black: 
![EDS](https://user-images.githubusercontent.com/48723686/95857926-50c7f000-0d2a-11eb-9093-e3e8eeaff6ee.PNG)
I am using a custom HUD color matrix, hence the question.

**Comment by Rhaedas** [comment] 2020-10-13 13:24
To answer the question, yes, one of the first additions to this program he put in was to see if a user had a custom HUD setup to try and match it.

**Comment by D4VID-B** [comment] 2020-10-13 14:10
Ah, nice touch!
So since this particular issue is more-or-less resolved, should I close it? Or do you have other plans for it?

**Comment by joncage** [comment] 2020-10-13 17:06
I have one more bit to add - Microsoft sent me an additional message I want to capture here after I disputed it.

..and yes, the colour matching is done so that the Scout matches your HUD. That was a fun one to implement! 👌🏻😊

**Comment by joncage** [comment] 2020-10-13 20:38
Here's what Microsoft said after I raised a dispute...

> Thank you for your recent inquiry about EDScout (submission reference: 6dc85a2b-6a84-44c8-9edd-59f2a6cef07e; file reference: [edscout.exe, cd63e536fe177452883eca53322bba3bb79334f3ab85a16acc6846544da2c207] )  in connection with the operation of Windows Defender.  
> 
> The new security intelligence update version 1.325.681.0 contains changes necessary to resolve your question relating to EDScout.  This new security intelligence update is now available for users who subscribe to the automatic security intelligence update mechanism, as well as users who choose to manually update their security intelligence update library.  
> 
> We encourage you to try this new security intelligence update and confirm your inquiry has been resolved.  If your machine has not been updated with this version of security intelligence update you can download and install the update manually following these steps:  
> 
> ·       Go to https://www.microsoft.com/en-us/wdsi/defenderupdates 
> ·       Download the corresponding definitions (32 bit or 64 bit based on your operating system)  
> ·       Run the downloaded file to install the new definitions  
> 
> We apologize for any inconvenience this may have caused.  If you have any additional questions related to this inquiry, please contact us at mpcreply@microsoft.com.  Should you need to contact us in the future regarding a question unrelated to this inquiry, please visit Microsoft Security Intelligence portal  https://www.microsoft.com/en-us/wdsi.  
> 
> Sincerely,  
> 
> Microsoft Defender Response

**Comment by joncage** [comment] 2020-10-13 20:40
Closing this now as that should hopefully be the end of it..

**Closed by joncage** 2020-10-13 20:40 UTC
