### ISSUE TITLE
1.5.1 Does Not Start

### ISSUE THREAD

**Issue by Ketris** [joncage/ed-scout#85] opened 2020-09-19 17:51 UTC
![image](https://user-images.githubusercontent.com/726660/93685690-d1bb0100-fa76-11ea-90f6-64f7a4e2fe0f.png)
Windows 10 build 20206.1000
Downloaded tagged 1.5.1 release just now (redownloaded twice to be sure)
Chrome is (and always was) installed and set as default browser.

**Comment by joncage** [comment] 2020-09-20 07:15
Duplicate of #86

**Closed by joncage** 2020-09-20 07:15 UTC
