### ISSUE TITLE
Gravity off by a decimal place

### ISSUE THREAD

**Issue by artig4n** [joncage/ed-scout#133] opened 2020-10-12 15:07 UTC
There's a new little gravity indicator on landables, but it's off by one decimal place. A .05G planet is showing as .5, for example. Cool feature though.

**Comment by joncage** [comment] 2020-10-12 16:20
Yep. Should be fixed as of 1.7.1 - turns out frontier quietly divide it by 10 in the logs!

**Comment by joncage** [comment] 2020-10-12 20:30
Closing as a duplicate of #124

**Closed by joncage** 2020-10-12 20:30 UTC
